package com.example.common

/**
 * ARouter的路径。
 */
interface ARouterPath {

    companion object {
        const val GROUP_MAIN: String = "Main"
        const val GROUP_DORA: String = "Dora"
        const val GROUP_CACHE: String = "Cache"
        const val GROUP_VIEW: String = "View"
        const val ACTIVITY_MENU_LIST: String = "/$GROUP_MAIN/MenuListActivity"
        const val ACTIVITY_INTRODUCE: String = "/$GROUP_DORA/IntroduceActivity"
        const val ACTIVITY_WEB_VIEW: String = "/$GROUP_DORA/WebViewActivity"
        const val ACTIVITY_EXTRAS: String = "/$GROUP_DORA/ExtrasActivity"
        const val ACTIVITY_EVENT_BUS: String = "/$GROUP_DORA/EventBusActivity"
        const val ACTIVITY_CRASH: String = "/$GROUP_DORA/CrashActivity"
        const val ACTIVITY_TIPS: String = "/$GROUP_DORA/TipsActivity"
        const val ACTIVITY_FLOW_PAGE: String = "/$GROUP_DORA/FlowPageActivity"
        const val ACTIVITY_NET_DETECT: String = "/$GROUP_DORA/NetDetectActivity"
        const val ACTIVITY_PGYER: String = "/$GROUP_DORA/PgyerActivity"
        const val ACTIVITY_VIEW_MODEL_SAMPLE_1: String =
            "/$GROUP_DORA/ViewModelSample1Activity"
        const val ACTIVITY_VIEW_MODEL_SAMPLE_2: String =
            "/$GROUP_DORA/ViewModelSample2Activity"
        const val ACTIVITY_RSA: String = "/$GROUP_DORA/RsaActivity"
        const val ACTIVITY_ROUTE: String = "/$GROUP_DORA/RouteActivity"
        const val ACTIVITY_WEB3_PAY: String = "/$GROUP_DORA/Web3PayActivity"
        const val ACTIVITY_ORM_INSERT_DATA: String = "/$GROUP_CACHE/OrmInsertDataActivity"
        const val ACTIVITY_ORM_UPDATE_DATA: String = "/$GROUP_CACHE/OrmUpdateDataActivity"
        const val ACTIVITY_ORM_QUERY_DATA: String = "/$GROUP_CACHE/OrmQueryDataActivity"
        const val ACTIVITY_ORM_DELETE_DATA: String = "/$GROUP_CACHE/OrmDeleteDataActivity"
        const val ACTIVITY_ORM_TRANSACTION: String = "/$GROUP_CACHE/OrmTransactionActivity"
        const val ACTIVITY_ORM_CONVERTER: String = "/$GROUP_CACHE/OrmConverterActivity"
        const val ACTIVITY_CACHE_NON_LIST_DATA: String = "/$GROUP_CACHE/CacheNonListDataActivity"
        const val ACTIVITY_CACHE_LIST_DATA: String = "/$GROUP_CACHE/CacheListDataActivity"
        const val ACTIVITY_CACHE_BATCH: String = "/$GROUP_CACHE/CacheBatchActivity"
        const val ACTIVITY_CACHE_PAGER: String = "/$GROUP_CACHE/CachePagerActivity"
//        const val ACTIVITY_DATA_CACHE: String = "/$GROUP_CACHE/DataCacheActivity"
        const val ACTIVITY_PROGRESS_VIEW: String = "/$GROUP_VIEW/ProgressViewActivity"
        const val ACTIVITY_TITLE_BAR: String = "/$GROUP_VIEW/TitleBarActivity"
        const val ACTIVITY_TOGGLE_BUTTON: String = "/$GROUP_VIEW/ToggleButtonActivity"
        const val ACTIVITY_TOAST: String = "/$GROUP_VIEW/TipsActivity"
        const val ACTIVITY_TAB_LAYOUT: String = "/$GROUP_VIEW/TabLayoutActivity"
        const val ACTIVITY_ALERT_DIALOG: String = "/$GROUP_VIEW/AlertDialogActivity"
        const val ACTIVITY_LOADING_DIALOG: String = "/$GROUP_VIEW/LoadingDialogActivity"
        const val ACTIVITY_BOTTOM_DIALOG: String = "/$GROUP_VIEW/BottomDialogActivity"
        const val ACTIVITY_RADIO_GROUP: String = "/$GROUP_VIEW/RadioGroupActivity"
        const val ACTIVITY_EMPTY_LAYOUT: String = "/$GROUP_VIEW/EmptyLayoutActivity"
        const val ACTIVITY_MENU_PANEL: String = "/$GROUP_VIEW/MenuPanelActivity"
        const val ACTIVITY_FLEXIBLE_SCROLL_VIEW: String = "/$GROUP_VIEW/FlexibleScrollViewActivity"
        const val ACTIVITY_SWIPE_LAYOUT: String = "/$GROUP_VIEW/SwipeLayoutActivity"
        const val ACTIVITY_GRID_VIEW: String = "/$GROUP_VIEW/GridViewActivity"
        const val ACTIVITY_COUPON_VIEW: String = "/$GROUP_VIEW/CouponViewActivity"
        const val ACTIVITY_FLOW_LAYOUT: String = "/$GROUP_VIEW/FlowLayoutActivity"
        const val ACTIVITY_ICON_LABEL: String = "/$GROUP_VIEW/IconLabelActivity"
        const val ACTIVITY_SWIPE_MENU: String = "/$GROUP_VIEW/SwipeMenuActivity"
        const val ACTIVITY_BADGE_VIEW: String = "/$GROUP_VIEW/BadgeViewActivity"
        const val ACTIVITY_BOTTOM_BAR: String = "/$GROUP_VIEW/BottomBarActivity"
        const val ACTIVITY_PROGRESS_BAR: String = "/$GROUP_VIEW/ProgressBarActivity"
        const val ACTIVITY_ADD_SUB_VIEW: String = "/$GROUP_VIEW/AddSubViewActivity"
        const val ACTIVITY_DROP_DOWN_LAYOUT: String = "/$GROUP_VIEW/DropDownLayoutActivity"
        const val ACTIVITY_CLEAR_EDIT_TEXT: String = "/$GROUP_VIEW/ClearEditTextActivity"
        const val ACTIVITY_CHARTS: String = "/$GROUP_VIEW/ChartsActivity"
        const val ACTIVITY_PINCH_ZOOM_LAYOUT: String = "/$GROUP_VIEW/PinchZoomLayoutActivity"
        const val ACTIVITY_SIDE_BAR: String = "/$GROUP_VIEW/SideBarActivity"
        const val ACTIVITY_SKELETON_VIEW: String = "/$GROUP_VIEW/SkeletonViewActivity"
        const val ACTIVITY_FLASH_VIEW: String = "/$GROUP_VIEW/FlashViewActivity"
        const val ACTIVITY_BUTTON: String = "/$GROUP_VIEW/ButtonActivity"
        const val ACTIVITY_FLIPPER_VIEW: String = "/$GROUP_VIEW/FlipperViewActivity"
        const val ACTIVITY_PARALLAX_LAYOUT: String = "/$GROUP_VIEW/ParallaxLayoutActivity"
        const val ACTIVITY_AVATAR: String = "/$GROUP_VIEW/AvatarActivity"
        const val ACTIVITY_ROTATE_VIEW: String = "/$GROUP_VIEW/RotateViewActivity"

        const val VIEW_SERVICE = "/$GROUP_VIEW/ViewProvider"
        const val DORA_SERVICE = "/$GROUP_DORA/DoraProvider"
        const val CACHE_SERVICE = "/$GROUP_CACHE/CacheProvider"
    }
}
