name: Android CI Build
on:
  #  workflow_dispatch:
  push:
    tags:
      - '*' # 当push标签时触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up output
        id: vars
        run: |
          echo "short_ref=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Checkout
        id: check
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build App
        run: |
          ./gradlew app:assembleRelease
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_DORA }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          overwrite: true
          files: 'app/build/outputs/apk/release/*.apk'
